image: node:14

stages:
  - Prepare
  - Lint
  - Test
  - Build
  - Security

cache: &global_cache
  key:
    files:
      - package-lock.json
  paths:
    - node_modules
  policy: pull

prepare:
  stage: Prepare
  cache:
    # inherit global_cache properties, override policy
    <<: *global_cache
    policy: pull-push
  script:
    - npm install

lint:
  except:
    - schedules
  stage: Lint
  before_script:
    - npm install
  script:
    - npm run lint:ci

test:
  except:
    - schedules
  stage: Test
  script:
    - npm run test:ci

build:
  except:
    - schedules
  stage: Build
  script:
    - npm run build

audit:
  except:
    - schedules
  stage: Security
  script:
    - npm audit

lockfile_lint:
  except:
    - schedules
  stage: Security
  script:
    - npm run lockfile-lint

snyk_test:
  only:
    refs:
      - schedules
    variables:
      - $IS_WEEKLY_RUN != "true"
  stage: Security
  before_script:
    - npm run snyk:auth "$SNYK_TOKEN"
  script:
    - npm run snyk:test

snyk_monitor:
  only:
    refs:
      - schedules
    variables:
      - $IS_WEEKLY_RUN == "true"
  stage: Security
  before_script:
    - npm run snyk:auth "$SNYK_TOKEN"
  script:
    - npm run snyk:monitor

