image: node:14

stages:
  - Prepare
  - Lint
  - Test
  - Build
  - Security
  - Deploy

cache: &global_cache
  key:
    files:
      - package-lock.json
  paths:
    - node_modules
  policy: pull

prepare:
  stage: Prepare
  cache:
    # inherit global_cache properties, override policy
    <<: *global_cache
    policy: pull-push
  script:
    - npm install
  dependencies: []

lint:
  except:
    - schedules
  stage: Lint
  script:
    - npm run eslint:ci
    - npm run stylelint:ci
  dependencies: []

test:
  except:
    - schedules
  stage: Test
  script:
    - npm run test:ci
  dependencies: []

build:
  except:
    - schedules
    - tags
  stage: Build
  script:
    - npm run build
  dependencies: []

build_prod:
  only:
    - tags
  stage: Build
  before_script:
    - echo "$ENV_FILE_PRODUCTION" > ./.env.production
  script:
    - npm run build
  artifacts:
    paths:
      - build/
  dependencies: []


audit:
  except:
    - schedules
  stage: Security
  script:
    - npm audit
  dependencies: []

lockfile_lint:
  except:
    - schedules
  stage: Security
  script:
    - npm run lockfile-lint
  dependencies: []

snyk_test:
  only:
    refs:
      - schedules
    variables:
      - $IS_WEEKLY_RUN != "true"
  stage: Security
  before_script:
    - npm run snyk:auth "$SNYK_TOKEN"
  script:
    - npm run snyk:test

snyk_monitor:
  only:
    refs:
      - schedules
    variables:
      - $IS_WEEKLY_RUN == "true"
  stage: Security
  before_script:
    - npm run snyk:auth "$SNYK_TOKEN"
  script:
    - npm run snyk:monitor

deploy:
  only:
    - tags
  stage: Deploy
  before_script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - echo "$SERVER_SSH_PRIVATE_KEY" | tr -d "\r" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan "$SERVER_URL" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp -r build "$SERVER_USER"@"$SERVER_URL":/home/$SERVER_USER/air-monitoring-frontend
    - ssh "$SERVER_USER"@"$SERVER_URL" "/home/$SERVER_USER/air-monitoring-frontend/redeploy.sh"
  dependencies:
    - build_prod
