image: node:14

stages:
  - Prepare
  - Lint
  - Test
  - Build
  - Audit

cache: &global_cache
  key:
    files:
      - package-lock.json
  paths:
    - node_modules
  policy: pull

prepare:
  stage: Prepare
  cache:
    # inherit global_cache properties, override policy
    <<: *global_cache
    policy: pull-push
  script:
    - npm install

lint:
  stage: Lint
  before_script:
    - npm install
  script:
    - npm run lint:ci

test:
  stage: Test
  script:
    - npm run test:ci

build:
  stage: Build
  script:
    - npm run build

audit:
  stage: Audit
  script:
    - npm audit
